# Generated by Django 4.2.9 on 2024-01-11 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_alter_data_end_year_alter_data_intensity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='added',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='published',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
