# Generated by Django 4.2.9 on 2024-01-11 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_alter_data_added_alter_data_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='end_year',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='start_year',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
