# Generated by Django 4.2.9 on 2024-01-11 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0006_alter_data_end_year_alter_data_start_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='impact',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
