# Generated by Django 4.2.9 on 2024-01-11 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0007_alter_data_impact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='published',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
